version: "3.5"
services:
  nginx:
    container_name: docker-nginx-container
    image: nginx:stable-alpine
    ports:
      - 8080:80

    volumes:
      - ./conf/:/etc/nginx/conf.d/:ro 
      - ./logs:/var/log/nginx/log
      - ./vhost:/etc/nginx/sites-available/:ro
      - ./vhost:/etc/nginx/sites-enabled/:ro
      - ./html/:/usr/share/nginx/html/:ro

networks:
  default:
    name: net_bridge
    external: true

     